query getAssetMarkets($asset: String!, $chainId: Int!) {
  markets(where: { chainId_in: [$chainId] collateralAssetAddress_in: [$asset] }) {
    items {
      id
      uniqueKey
      lltv
      oracleAddress
      irmAddress
      collateralPrice
      morphoBlue {
        id
        address
      }
      loanAsset {
        id
        address
        symbol
        name
        decimals
        priceUsd
      }
      collateralAsset {
        id
        address
        symbol
        name
        decimals
        priceUsd
      }
      dailyApys {
        borrowApy
        netBorrowApy
      }
      weeklyApys {
        borrowApy
        netBorrowApy
      }
      monthlyApys {
        borrowApy
        netBorrowApy
      }
      state {
        borrowApy
        netBorrowApy
      }
    }
  }
}
