query getUserMarketPosition($user: String!, $market: String!, $chainId: Int!) {
  marketPosition(userAddress: $user, marketUniqueKey: $market, chainId: $chainId) {
      id
      borrowShares
      borrowAssets
      borrowAssetsUsd
      collateral
      collateralUsd
      market {
        id
        uniqueKey
        lltv
        oracleAddress
        irmAddress
        collateralPrice
        morphoBlue {
          id
          address
        }
        loanAsset {
          id
          address
          symbol
          name
          decimals
          priceUsd
        }
        collateralAsset {
          id
          address
          symbol
          name
          decimals
          priceUsd
        }
        dailyApys {
          borrowApy
          netBorrowApy
        }
        weeklyApys {
          borrowApy
          netBorrowApy
        }
        monthlyApys {
          borrowApy
          netBorrowApy
        }
        state {
          borrowApy
          netBorrowApy
        }
      }
      user {
        id
        address
        tag
        chain {
          id
        }
      }
    }
}
