query getUserMarketPositions($address: String!, $chainId: Int!) {
  userByAddress(address: $address, chainId: $chainId) {
    id
    marketPositions {
      id
      borrowShares
      borrowAssets
      borrowAssetsUsd
      collateral
      collateralUsd
      market {
        id
        uniqueKey
        lltv
        oracleAddress
        irmAddress
        morphoBlue {
          id
          address
          chain {
            id
          }
        }
        loanAsset {
          id
          address
          symbol
          name
          decimals
          priceUsd
        }
        collateralAsset {
          id
          address
          symbol
          name
          decimals
          priceUsd
        }
      }
      user {
        id
        address
        tag
        chain {
          id
        }
      }
    }
  }
}
